### ISSUE TITLE
Create Main Page with Input Form

### ISSUE THREAD

**Issue by jorbush** [JAM-Productions/dinoshort#2]
**Description:**
Develop the main page of DinoShort featuring a form with an input field for the URL and a "Generate" button.

**Tasks:**
- [ ] Create the basic design of the main page following the mockup using Astro and TailwindCSS.
- [ ] Implement an input field for the URL with TypeScript.
- [ ] Implement a "Generate" button to trigger URL shortening.
- [ ] Add the DinoShort logo at the top.
- [ ] Add the credit text "JAM-Productions ©2024" at the bottom.

Remember create components when is needed and you can use React, Svelte, Vue, ...
