### ISSUE TITLE
Implement Redirection from Short Link

### ISSUE THREAD

**Issue by jorbush** [JAM-Productions/dinoshort#5]
**Description:**
Set up automatic redirection so that accessing a short link redirects to the original URL.

**Tasks:**
- [ ] Configure the backend with Astro and TypeScript to capture accesses to `https://dinoshort.vercel.app/{url}`.
- [ ] Retrieve the original URL from Upstash Redis database associated with the identifier.
- [ ] Implement the logic to redirect the user to the original URL.
