### ISSUE TITLE
Add Dark Mode Support

### ISSUE THREAD

**Issue by jorbush** [JAM-Productions/dinoshort#7]
**Description:**
Implement a button to toggle between light and dark modes in the application.

**Tasks:**
- [ ] Add a dark mode icon in the top right corner.
- [ ] Implement TailwindCSS styles for dark mode.
- [ ] Implement the logic with TypeScript to toggle between light and dark modes.
